name: my-front
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
      AWS_REGION: 'ap-northeast-2'

    steps:
      - name: Checkout source code.
        uses: actions/checkout@master

      - name: Upload binary to S3 bucket
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --include '*' --exclude '.git*/*' --exclude '.git*'
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}

      - name: CloudFront Invalidation
        env:
          CLOUD_FRONT_ID: ${{ secrets.DISTRIBUTION_ID}}
        run: |
          aws cloudfront create-invalidation \
          --distribution-id $CLOUD_FRONT_ID --paths /*

      - name: Invalidate cache CloudFront
        uses: chetan/invalidate-cloudfront-action@master
        env:
          DISTRIBUTION: ${{ secrets.DISTRIBUTION_ID }}
          PATHS: '/index.html'
        continue-on-error: true

      - name: Slack - Send Msg
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: workflow,job,commit,repo,author,took,ref
          author_name: miyeong
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.Slack_URL }}
        if: always()
